version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile

  nginx:
    container_name: middlenginx
    image: nginx:stable-alpine
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
      - mariadb
    ports:
      - "8080:8080"

  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: kanban_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"