version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
#    image: andreasredekerregistry.azurecr.io/kanban-frontend

  nginx:
    container_name: middlenginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
#    image: andreasredekerregistry.azurecr.io/middlenginx
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
#    image: andreasredekerregistry.azurecr.io/kanban-backend
    depends_on:
      - mariadb
    ports:
      - "8080:8080"

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: kanban_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"