version: '3'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: kanban_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
      - mariadb
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"